// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using reddit_capstone;

namespace sdgreacttemplate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("StackOverFlow.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<int>("DownVote");

                    b.Property<int?>("PostID");

                    b.Property<string>("PostedBy");

                    b.Property<DateTime>("TimePassed");

                    b.Property<int>("UpVote");

                    b.HasKey("ID");

                    b.HasIndex("PostID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("StackOverFlow.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<int>("DownVote");

                    b.Property<string>("PostedBy");

                    b.Property<DateTime>("TimePassed");

                    b.Property<string>("Title");

                    b.Property<int>("UpVote");

                    b.HasKey("ID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("StackOverFlow.Models.Comment", b =>
                {
                    b.HasOne("StackOverFlow.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID");
                });
#pragma warning restore 612, 618
        }
    }
}
